const matchConstants = {
    CREATE_MATCH_API_SUCCESS: "CREATE_MATCH_API_SUCCESS",
    PLAYERS_API_SUCCESS:"PLAYERS_API_SUCCESS",
    SET_MATCH:"SET_MATCH",
    SET_FIRSTINNING:"SET_FIRSTINNING",
    SET_SECONDINNING:"SET_SECONDINNING",
    SET_TEAMONE:"SET_TEAMONE",
    SET_TEAMTWO:"SET_TEAMTWO",
    UPDATE_CURRENT_OVER:"UPDATE_CURRENT_OVER",
    CHANGE_TEAMS:"CHANGE_TEAMS"
};
  
export default matchConstants;